domain: 'http://localhost'
url: 'http://localhost/'

site_name: 'template'

# meta_description: 'description'
# meta_keywords: ['key' 'words']

# share_image: 'http://localhost/img/ogp.png'

# og_description: 'description'
# og_image_width: 0
# og_image_height: 0

# tw_description: 'description'
# tw_hashtags: ['hashtag']
# tw_site: '@hoge'
# tw_creator: '@hoge'

# line_description: 'description http://localhost/'

# fb_appid: ''

# favicon_url: 'http://localhost/favicon.ico'
# apple_touch_icon_url: 'http://localhost/favicon.ico'
